version: '3.8'
services:
  web:
    build: .
    command: gunicorn student_budget.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - oracle
  oracle:
    image: gvenzl/oracle-xe:18.0.0-slim
    environment:
      - ORACLE_PASSWORD=oracle
    ports:
      - "1521:1521"
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1 FROM dual;' | sqlplus -s system/oracle@//localhost:1521/XE" ]
      interval: 30s
      timeout: 10s
      retries: 10
